Use SalesDB
Go

-- USE CASE: GENERATE A REPORT SHOWING THE TOTAL SALES FOR EACH CATEGORY 

-- - HIGH: IF THE SALES HIGHER THAN 50
-- - MEDIUM: IF THE SALES BETWEEN 20 AND 50
-- - LOW: IF THE SALES EQUAL OR LOWER THAN 20

-- SORT THE RESULT FROM LOWEST TO HIGHEST

SELECT
OrderID,
PRODUCTID,
SALES,
CASE 
WHEN SALES >= 60 THEN 'HIGH'
WHEN SALES >= 20 and SALES <= 50 THEN 'MEDIUM'
WHEN SALES < 20 THEN 'LOW'
END AS 'Category' 
FROM SALES.Orders
